edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
