name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly-2022-08-09
          override: true
          profile: minimal
          components: rustfmt, clippy, miri, rust-src
    - name: Install SARIF support
      run: cargo install clippy-sarif sarif-fmt
    - name: Clippy
      run: cargo clippy --all-features --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      continue-on-error: true
    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: rust-clippy-results.sarif
        wait-for-processing: true
    - name: Check formatting
      run: cargo fmt --check
    - name: Check README.md
      run: diff README.md <(cat readme-parts/{header,main,license}.md)
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run doctests
      run: cargo test --doc --verbose
    - name: Run miri
      run: cargo miri test -- --skip ui
    - name: Run miri doctests
      run: cargo miri test --doc
  build_stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustc, cargo
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      # UI tests are too brittle to run them on two different toolchains
      run: cargo test --verbose -- --skip ui
    - name: Run doctests
      run: cargo test --doc --verbose
